messages:
  prefix: "&6[&cREGISTER&6] "
  no-permission: "&aYou don't have permission to do that."
  no-console: "&aYou can't run that command as console."
  login-required-e: "&aYou need to login! /login <password>"
  login-required-first: "&aOops, looks like your IP has changed. Please login /login <password>"
  register-required: "&aOops, looks like you need to register. /register <password> <password>"
  register-help: "&aOops, incorrect usage. Try /register <password> <password>"
  register-success: "&aYou've successfully register with the password of %password%"
  already-registered: "&aSorry, you've already registered."
  register-invalid: "&aSorry, both passwords must be the same."
  already-logged: "&aHey! You've already logged in."
  login-help: "&aOops, incorrect usage. Try /login <password>"
  login-wrong: "&aOops, that's not the correct password. Is this really you?"
  login-success: "&aAlright, you're clear. Proceeeeeeeeed"